import React, { useState } from "react";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>VisFork</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1 className="text-xl">
					<a href="./example">Example: d3 - stargazer counts of forks</a>
				</h1>
				<h1 className="text-xl">
					<a href="./api/forks?repo=iina/iina">Example: serverless api - fetch forks</a>
				</h1>
				<h1 className="text-xl">
					<a href="./api/hello">Example: serverless api - hello</a>
				</h1>
			</main>
		</>
	);
}
