import React from "react";
import Head from "next/head";
import GitHubIcon from '@mui/icons-material/GitHub';

export default function Home() {
	return (
		<>
			<Head>
				<title>VisFork</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1><GitHubIcon sx={{ fontSize: 70 }}/></h1>
				<h3 className="text-xl underline">
					<a href="./example">Example: d3 - stargazer counts of forks</a>
				</h3>
				<h3 className="text-xl underline">
					<a href="./api/forks?repo=iina/iina">Example: serverless api - fetch forks</a>
				</h3>
				<h3 className="text-xl underline">
					<a href="./api/hello">Example: serverless api - hello</a>
				</h3>
			</main>
		</>
	);
}
